version: '3'
services:

  dungeonsheets:
    build: ./
    volumes:
      - ./brouse:/examples
      - ./dungeonsheets:/usr/local/lib/python3.7/site-packages/dungeonsheets-0.6.1-py3.7.egg/dungeonsheets/
    command: -e ${CHARACTER}.py
    entrypoint: makesheets 
