version: '3'
services:

  dungeonsheets:
    build: ./
    volumes:
      - ./examples:/examples
    #command: -e ${CHARACTER}.py
    #entrypoint: makesheets 
    command: blank-character-sheet-default.pdf dump_data_fields
    entrypoint: pdftk 
